using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using JsonSubTypes;
using Newtonsoft.Json;

using Bitmovin.Api.Sdk.Common;
using Bitmovin.Api.Sdk.Models;

namespace Bitmovin.Api.Sdk.Models
{
    /// <summary>
    /// EncodingStatistics
    /// </summary>
    public class EncodingStatistics
    {
        /// <summary>
        /// Date, format. yyyy-MM-dd (required)
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public DateTime? Date { get; internal set; }

        /// <summary>
        /// Bytes encoded for this encoding. (required)
        /// </summary>
        [JsonProperty(PropertyName = "bytesEncoded")]
        public long? BytesEncoded { get; internal set; }

        /// <summary>
        /// Time in seconds encoded for this encoding. (required)
        /// </summary>
        [JsonProperty(PropertyName = "timeEncoded")]
        public long? TimeEncoded { get; internal set; }

        /// <summary>
        /// Egress output generated by file transfers in bytes (required)
        /// </summary>
        [JsonProperty(PropertyName = "bytesEgress")]
        public long? BytesEgress { get; internal set; }

        /// <summary>
        /// BillableEncodingMinutes
        /// </summary>
        [JsonProperty(PropertyName = "billableEncodingMinutes")]
        public List<BillableEncodingMinutes> BillableEncodingMinutes { get; set; } = new List<BillableEncodingMinutes>();

        /// <summary>
        /// BillableEgressBytes
        /// </summary>
        [JsonProperty(PropertyName = "billableEgressBytes")]
        public List<EgressInformation> BillableEgressBytes { get; set; } = new List<EgressInformation>();

        /// <summary>
        /// Streams
        /// </summary>
        [JsonProperty(PropertyName = "streams")]
        public List<StatisticsPerStream> Streams { get; set; } = new List<StatisticsPerStream>();

        /// <summary>
        /// Muxings
        /// </summary>
        [JsonProperty(PropertyName = "muxings")]
        public List<StatisticsPerMuxing> Muxings { get; set; } = new List<StatisticsPerMuxing>();

        /// <summary>
        /// Features
        /// </summary>
        [JsonProperty(PropertyName = "features")]
        public List<BillableEncodingFeatureMinutes> Features { get; set; } = new List<BillableEncodingFeatureMinutes>();

        /// <summary>
        /// Billable minutes for the muxings.
        /// </summary>
        [JsonProperty(PropertyName = "billableTransmuxingMinutes")]
        public double? BillableTransmuxingMinutes { get; internal set; }

        /// <summary>
        /// Billable minutes for the features.
        /// </summary>
        [JsonProperty(PropertyName = "billableFeatureMinutes")]
        public double? BillableFeatureMinutes { get; internal set; }
    }
}
