using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using JsonSubTypes;
using Newtonsoft.Json;

using Bitmovin.Api.Sdk.Common;
using Bitmovin.Api.Sdk.Models;

namespace Bitmovin.Api.Sdk.Models
{
    /// <summary>
    /// Statistics
    /// </summary>
    public class Statistics
    {
        /// <summary>
        /// Bytes encoded total. (required)
        /// </summary>
        [JsonProperty(PropertyName = "bytesEncodedTotal")]
        public long? BytesEncodedTotal { get; internal set; }

        /// <summary>
        /// Time in seconds encoded for all contained daily statistics. (required)
        /// </summary>
        [JsonProperty(PropertyName = "timeEncodedTotal")]
        public long? TimeEncodedTotal { get; internal set; }

        /// <summary>
        /// Egress output generated by file transfers in bytes
        /// </summary>
        [JsonProperty(PropertyName = "bytesEgressTotal")]
        public long? BytesEgressTotal { get; internal set; }
    }
}
